---
user_home_path: "{{ lookup('env', 'HOME') }}"
drupal_env: "{{ lookup('env', 'ENV') }}"

# GIT
git_packages:
  - git

# WEB SERVER
www_owner: "root"
www_group: "www-data"

# DRUPAL
enable_debug: no
drupal_project_path: "/app"

# DRUPAL KRAFTWAGEN
drupal_path: "/app/build"
drupal_project_path: "/app"
drupal_source: https://github.com/TallerWebSolutions/teste.git
drupal_www_owner: "{{ www_owner }}"
drupal_admin_password: "passwagen"
drupal_admin_email: admin@localhost.com
drupal_site_name: "Drucker Test"
drupal_kw_name: druckertest
drupal_kw_human_name: "Drucker Test"
drupal_kw_source: https://github.com/TallerWebSolutions/kraftwagen.git
drupal_kw_source_branch: taller
drupal_kw_skeleton_source: https://github.com/TallerWebSolutions/kraftwagen-default-skeleton.git
drupal_kw_skeleton_branch: basic
drupal_db:
  driver: mysql
  user: "{{ lookup('env', 'DB_ENV_MYSQL_USER') }}"
  password: "{{ lookup('env', 'DB_ENV_MYSQL_PASSWORD') }}"
  database: "{{ lookup('env', 'DB_ENV_MYSQL_DATABASE') }}"
  host: "{{ lookup('env', 'DB_PORT_3306_TCP_ADDR') }}"
  port: "{{ lookup('env', 'DB_PORT_3306_TCP_PORT') }}"
  prefix: ""

# PHP COMPOSER
composer_user: "{{ www_owner }}"
composer_user_home: "/root"

# PHP-FPM
php_fpm_apt_packages:
  - php5-fpm
  - php5-cli
  - php5-gd
  - php5-mysql
  - php5-mcrypt
  - php5-dev
  - php-pear
  - php-apc
  - php5-curl
  - php-mail

php_fpm_config:
  - option: "emergency_restart_threshold"
    section: "global"
    value: "10"
  - option: "emergency_restart_interval"
    section: "global"
    value: "1m"
  - option: "process_control_timeout"
    section: "global"
    value: "5"
  - option: "daemonize"
    section: "global"
    value: "no"

php_fpm_ini:
  - option: "memory_limit"
    section: "PHP"
    value: "512M"
  - option: "engine"
    section: "PHP"
    value: "1"
  - option: "error_reporting"
    section: "PHP"
    value: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
  - option: "ldap.max_links"
    section: "ldap"
    value: "1"
  - option: "max_execution_time"
    section: "PHP"
    value: "60"
  - option: "upload_max_filesize"
    section: "PHP"
    value: "64M"
  - option: "date.timezone"
    section: "Date"
    value: "America/Sao_Paulo"
    # APC related configuration.
  - option: "apc.shm_size"
    section: "APC"
    value: "96M"
  - option: "apc.shm_segments"
    section: "APC"
    value: "1"
  - option: "apc.num_files_hint"
    section: "APC"
    value: "2048"
  - option: "apc.user_entries_hint"
    section: "APC"
    value: "4096"
  - option: "apc.ttl"
    section: "APC"
    value: "7200"
  - option: "apc.use_request_time"
    section: "APC"
    value: "1"
  - option: "apc.user_ttl"
    section: "APC"
    value: "7200"
  - option: "apc.gc_ttl"
    section: "APC"
    value: "3600"
  - option: "apc.mmap_file_mask"
    section: "APC"
    value: "/tmp/apc.XXXXXX"
  - option: "apc.file_update_protection"
    section: "APC"
    value: "2"
  - option: "apc.enable_cli"
    section: "APC"
    value: "1"
  - option: "apc.max_file_size"
    section: "APC"
    value: "1M"
  - option: "apc.stat"
    section: "APC"
    value: "1"
  - option: "apc.stat_ctime"
    section: "APC"
    value: "0"
  - option: "apc.canonicalize"
    section: "APC"
    value: "0"
  - option: "apc.write_lock"
    section: "APC"
    value: "1"
  - option: "apc.report_autofilter"
    section: "APC"
    value: "0"
  - option: "apc.rfc1867"
    section: "APC"
    value: "1"
  - option: "apc.rfc1867_prefix"
    section: "APC"
    value: "upload_"
  - option: "apc.rfc1867_name"
    section: "APC"
    value: "APC_UPLOAD_PROGRESS"
  - option: "apc.rfc1867_freq"
    section: "APC"
    value: "0"
  - option: "apc.rfc1867_ttl"
    section: "APC"
    value: "3600"
  - option: "apc.include_once_override"
    section: "APC"
    value: "0"
  - option: "apc.lazy_classes"
    section: "APC"
    value: "0"
  - option: "apc.lazy_functions"
    section: "APC"
    value: "0"
  - option: "apc.coredump_unmap"
    section: "APC"
    value: "0"
  - option: "apc.file_md5"
    section: "APC"
    value: "0"

php_fpm_pools:
  - name: www0
    listen: /var/run/php-fpm.sock
    user: "{{ www_group }}"
    group: "{{ www_group }}"
    listen.owner: "{{ www_group }}"
    listen.group: "{{ www_group }}"
    pm: dynamic
    pm.max_children: 5
    pm.start_servers: 2
    pm.min_spare_servers: 1
    pm.max_spare_servers: 3
    chdir: /

  - name: www1
    listen: /var/run/php-fpm-zwei.sock
    user: "{{ www_group }}"
    group: "{{ www_group }}"
    listen.owner: "{{ www_group }}"
    listen.group: "{{ www_group }}"
    pm: dynamic
    pm.max_children: 5
    pm.start_servers: 2
    pm.min_spare_servers: 1
    pm.max_spare_servers: 3
    chdir: /

  - name: www-bkp
    listen: /var/run/php-fpm-bkp.sock
    user: "{{ www_group }}"
    group: "{{ www_group }}"
    listen.owner: "{{ www_group }}"
    listen.group: "{{ www_group }}"
    pm: dynamic
    pm.max_children: 5
    pm.start_servers: 2
    pm.min_spare_servers: 1
    pm.max_spare_servers: 3
    chdir: /

# NGINX
nginx_log_dir: "/var/log/nginx"
nginx_http_params:
  - sendfile "on"
  - tcp_nopush "on"
  - tcp_nodelay "on"
  - keepalive_timeout "65"
  - access_log "{{ nginx_log_dir }}/access.log"
  - error_log "{{ nginx_log_dir }}/error.log"
  - types_hash_max_size "2048"
  - types_hash_bucket_size "32"
ubuntu_pkg:
  - python-selinux
  - nginx-extras

# NGINX-DRUPAL
nginx_http_pre_params:
  - types_hash_max_size "2048"
  - types_hash_bucket_size "32"
nginx_drupal_use_drush: false
nginx_drupal_microcache: false
nginx_drupal_flv_streaming: false
nginx_drupal_mp4_streaming: false
nginx_drupal_aio: false
nginx_drupal_http_core:
  client_max_body_size: "10m"
nginx_drupal_upstream_servers:
  - "unix:/var/run/php-fpm.sock"
  - "unix:/var/run/php-fpm-zwei.sock"
nginx_drupal_upstream_backup_servers:
  - "unix:/var/run/php-fpm-bkp.sock"
nginx_drupal_sites:
  - file_name: default
    root: "{{ drupal_path }}"
    http:
      port: 80
    # @TODO: Change to the domain.
    server_name: "_"
    default: true
    not_allowed_methods: none